# Generated by Django 4.2.3 on 2023-07-04 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person_name', models.CharField(max_length=200)),
                ('email_id', models.EmailField(max_length=200)),
                ('mobile_no', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=200)),
                ('hotel_city', models.CharField(max_length=200)),
                ('hotel_address', models.CharField(max_length=200)),
                ('hotel_amenities', models.CharField(max_length=200)),
                ('hotel_websiteurl', models.URLField()),
            ],
        ),
    ]
