# Generated by Django 4.2.3 on 2023-07-04 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='contact_person_name',
            new_name='person_name',
        ),
    ]
